/*
 *****************************************************************************************************
    NB: This function is autogenerated, please do not modify it manually. Generated on: 29-jun-2023.
 *****************************************************************************************************
 */

//prettier-ignore
/**
 * Returns a pointer to the static resource and its length.
 * @returns {[pointer, length]:Array<u32>}
 */
import {sampleStaticResource} from "./statc-resource-sample";

/**
 *
 * @param id
 */
export function getStaticResource(id:i32): usize[]  {

  // TODO: add `if()` or `switch()` to return different static resources

  return sampleStaticResource
}
